name: "Setup Android Environment"
description: "Checkout, JDK setup, Gradle setup"
inputs:
  fetch-depth:
    description: "Fetch depth for checkout"
    required: false
    default: "0"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache Android SDK
      uses: actions/cache@v4
      with:
        path: android-sdk
        key: androidsdk-${{ runner.os }}-api36-${{ hashFiles('scripts/ci/setup-android-sdk.sh') }}
        restore-keys: |
          androidsdk-${{ runner.os }}-api36-
          androidsdk-${{ runner.os }}-

    - name: Setup Android SDK
      shell: bash
      env:
        ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        ANDROID_API_LEVEL: "36"
      run: |
        set -euo pipefail
        chmod +x ./scripts/ci/setup-android-sdk.sh
        ./scripts/ci/setup-android-sdk.sh

        # Make the SDK discoverable for subsequent workflow steps.
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> "$GITHUB_ENV"
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> "$GITHUB_ENV"
        echo "$ANDROID_SDK_ROOT/platform-tools" >> "$GITHUB_PATH"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
